[package]
name = "dioxus-hmr"
version = "0.1.0"
edition = "2021"
description = ""
authors = ["Dioxus"]

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus" }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus" }
